import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>
        <div className="app-frame">
          <header className="app-topbar">
            <div className="app-topbar__inner">
              <div className="app-brand">
                <span className="app-brand__mark">QA</span>
                <div className="app-brand__text">
                  <span className="app-brand__title">Quality Adalta</span>
                  <span className="app-brand__subtitle">Operations dashboard</span>
                </div>
              </div>

              <div className="app-chip">Fluxo de serviços e documentação</div>
            </div>
          </header>

          {children}
        </div>
      </body>
    </html>
  );
}
