create table if not exists public.modelo_anexo_campos (
  id bigint generated by default as identity primary key,
  modelo_secao_id bigint not null references public.modelo_anexo_secoes(id) on delete cascade,
  nome text not null,
  label text,
  tipo text not null default 'text',
  opcoes text,
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (modelo_secao_id, nome)
);

create index if not exists modelo_anexo_campos_modelo_secao_id_idx
  on public.modelo_anexo_campos (modelo_secao_id);

alter table public.modelo_anexo_campos enable row level security;

drop policy if exists "authenticated read modelo_anexo_campos" on public.modelo_anexo_campos;
create policy "authenticated read modelo_anexo_campos"
on public.modelo_anexo_campos
for select
to authenticated
using (true);

drop policy if exists "authenticated insert modelo_anexo_campos" on public.modelo_anexo_campos;
create policy "authenticated insert modelo_anexo_campos"
on public.modelo_anexo_campos
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update modelo_anexo_campos" on public.modelo_anexo_campos;
create policy "authenticated update modelo_anexo_campos"
on public.modelo_anexo_campos
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete modelo_anexo_campos" on public.modelo_anexo_campos;
create policy "authenticated delete modelo_anexo_campos"
on public.modelo_anexo_campos
for delete
to authenticated
using (true);
