create table if not exists public.modelo_tipos_relatorio (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.modelo_qualificacao_modalidades (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.modelo_qualificacao_tipos (
  id bigint generated by default as identity primary key,
  modalidade_id bigint not null references public.modelo_qualificacao_modalidades(id) on delete cascade,
  nome text not null,
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  unique (modalidade_id, nome)
);

create table if not exists public.modelo_anexos (
  id bigint generated by default as identity primary key,
  qualificacao_tipo_id bigint not null references public.modelo_qualificacao_tipos(id) on delete cascade,
  nome text not null,
  descricao text,
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (qualificacao_tipo_id, nome)
);

create index if not exists modelo_qualificacao_tipos_modalidade_id_idx
  on public.modelo_qualificacao_tipos (modalidade_id);

create index if not exists modelo_anexos_qualificacao_tipo_id_idx
  on public.modelo_anexos (qualificacao_tipo_id);

insert into public.modelo_tipos_relatorio (nome, ordem)
values
  ('Avaliação', 1),
  ('Comissionamento', 2),
  ('TAB', 3),
  ('Qualificação', 4)
on conflict (nome) do update
set ordem = excluded.ordem;

insert into public.modelo_qualificacao_modalidades (nome, ordem)
values
  ('HVAC', 1),
  ('Equipamentos', 2),
  ('Gases', 3)
on conflict (nome) do update
set ordem = excluded.ordem;

insert into public.modelo_qualificacao_tipos (modalidade_id, nome, ordem)
select modalidade.id, tipo.nome, tipo.ordem
from public.modelo_qualificacao_modalidades modalidade
join (
  values
    ('HVAC', 'IQ', 1),
    ('HVAC', 'OQ', 2),
    ('HVAC', 'PQ', 3)
) as tipo(modalidade_nome, nome, ordem)
  on tipo.modalidade_nome = modalidade.nome
on conflict (modalidade_id, nome) do update
set ordem = excluded.ordem;

insert into public.modelo_anexos (qualificacao_tipo_id, nome, descricao, ordem, ativo)
select tipo.id, anexo.nome, anexo.descricao, anexo.ordem, true
from public.modelo_qualificacao_tipos tipo
join public.modelo_qualificacao_modalidades modalidade
  on modalidade.id = tipo.modalidade_id
join (
  values
    ('Startup de UTA', 'Anexo inicial para partida da UTA.', 1),
    ('Inspeção de operação de UTA', 'Checklist operacional da UTA.', 2),
    ('Startup de ventiladores e exaustores', 'Anexo inicial para partida de ventiladores e exaustores.', 3),
    ('Inspeção de operação de ventiladores e exaustores', 'Checklist operacional de ventiladores e exaustores.', 4)
) as anexo(nome, descricao, ordem)
  on true
where modalidade.nome = 'HVAC'
  and tipo.nome = 'OQ'
on conflict (qualificacao_tipo_id, nome) do update
set descricao = excluded.descricao,
    ordem = excluded.ordem,
    ativo = excluded.ativo;

alter table public.modelo_tipos_relatorio enable row level security;
alter table public.modelo_qualificacao_modalidades enable row level security;
alter table public.modelo_qualificacao_tipos enable row level security;
alter table public.modelo_anexos enable row level security;

drop policy if exists "authenticated read modelo_tipos_relatorio" on public.modelo_tipos_relatorio;
create policy "authenticated read modelo_tipos_relatorio"
on public.modelo_tipos_relatorio
for select
to authenticated
using (true);

drop policy if exists "authenticated insert modelo_tipos_relatorio" on public.modelo_tipos_relatorio;
create policy "authenticated insert modelo_tipos_relatorio"
on public.modelo_tipos_relatorio
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update modelo_tipos_relatorio" on public.modelo_tipos_relatorio;
create policy "authenticated update modelo_tipos_relatorio"
on public.modelo_tipos_relatorio
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete modelo_tipos_relatorio" on public.modelo_tipos_relatorio;
create policy "authenticated delete modelo_tipos_relatorio"
on public.modelo_tipos_relatorio
for delete
to authenticated
using (true);

drop policy if exists "authenticated read modelo_qualificacao_modalidades" on public.modelo_qualificacao_modalidades;
create policy "authenticated read modelo_qualificacao_modalidades"
on public.modelo_qualificacao_modalidades
for select
to authenticated
using (true);

drop policy if exists "authenticated insert modelo_qualificacao_modalidades" on public.modelo_qualificacao_modalidades;
create policy "authenticated insert modelo_qualificacao_modalidades"
on public.modelo_qualificacao_modalidades
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update modelo_qualificacao_modalidades" on public.modelo_qualificacao_modalidades;
create policy "authenticated update modelo_qualificacao_modalidades"
on public.modelo_qualificacao_modalidades
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete modelo_qualificacao_modalidades" on public.modelo_qualificacao_modalidades;
create policy "authenticated delete modelo_qualificacao_modalidades"
on public.modelo_qualificacao_modalidades
for delete
to authenticated
using (true);

drop policy if exists "authenticated read modelo_qualificacao_tipos" on public.modelo_qualificacao_tipos;
create policy "authenticated read modelo_qualificacao_tipos"
on public.modelo_qualificacao_tipos
for select
to authenticated
using (true);

drop policy if exists "authenticated insert modelo_qualificacao_tipos" on public.modelo_qualificacao_tipos;
create policy "authenticated insert modelo_qualificacao_tipos"
on public.modelo_qualificacao_tipos
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update modelo_qualificacao_tipos" on public.modelo_qualificacao_tipos;
create policy "authenticated update modelo_qualificacao_tipos"
on public.modelo_qualificacao_tipos
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete modelo_qualificacao_tipos" on public.modelo_qualificacao_tipos;
create policy "authenticated delete modelo_qualificacao_tipos"
on public.modelo_qualificacao_tipos
for delete
to authenticated
using (true);

drop policy if exists "authenticated read modelo_anexos" on public.modelo_anexos;
create policy "authenticated read modelo_anexos"
on public.modelo_anexos
for select
to authenticated
using (true);

drop policy if exists "authenticated insert modelo_anexos" on public.modelo_anexos;
create policy "authenticated insert modelo_anexos"
on public.modelo_anexos
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update modelo_anexos" on public.modelo_anexos;
create policy "authenticated update modelo_anexos"
on public.modelo_anexos
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete modelo_anexos" on public.modelo_anexos;
create policy "authenticated delete modelo_anexos"
on public.modelo_anexos
for delete
to authenticated
using (true);
