alter table public.documentacoes
  add column if not exists modo_criacao_documentacao text not null default 'por_sistema';

alter table public.documentacoes
  drop constraint if exists documentacoes_modo_criacao_documentacao_check;

alter table public.documentacoes
  add constraint documentacoes_modo_criacao_documentacao_check
  check (modo_criacao_documentacao in ('agrupado', 'por_sistema'));

create table if not exists public.documentacao_sistemas (
  id bigint generated by default as identity primary key,
  documentacao_id bigint not null references public.documentacoes(id) on delete cascade,
  sistema_id bigint not null references public.sistemas(id) on delete cascade,
  principal boolean not null default false,
  created_at timestamptz not null default now(),
  unique (documentacao_id, sistema_id)
);

create index if not exists documentacao_sistemas_documentacao_id_idx
  on public.documentacao_sistemas (documentacao_id);

create index if not exists documentacao_sistemas_sistema_id_idx
  on public.documentacao_sistemas (sistema_id);

insert into public.documentacao_sistemas (documentacao_id, sistema_id, principal)
select d.id, d.sistema_id, true
from public.documentacoes d
where d.sistema_id is not null
  and not exists (
    select 1
    from public.documentacao_sistemas ds
    where ds.documentacao_id = d.id
      and ds.sistema_id = d.sistema_id
  );
