create table if not exists public.modelo_anexo_secoes (
  id bigint generated by default as identity primary key,
  modelo_anexo_id bigint not null references public.modelo_anexos(id) on delete cascade,
  nome text not null,
  ordem integer not null default 0,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (modelo_anexo_id, nome)
);

create index if not exists modelo_anexo_secoes_modelo_anexo_id_idx
  on public.modelo_anexo_secoes (modelo_anexo_id);

alter table public.modelo_anexo_secoes enable row level security;

drop policy if exists "authenticated read modelo_anexo_secoes" on public.modelo_anexo_secoes;
create policy "authenticated read modelo_anexo_secoes"
on public.modelo_anexo_secoes
for select
to authenticated
using (true);

drop policy if exists "authenticated insert modelo_anexo_secoes" on public.modelo_anexo_secoes;
create policy "authenticated insert modelo_anexo_secoes"
on public.modelo_anexo_secoes
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update modelo_anexo_secoes" on public.modelo_anexo_secoes;
create policy "authenticated update modelo_anexo_secoes"
on public.modelo_anexo_secoes
for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated delete modelo_anexo_secoes" on public.modelo_anexo_secoes;
create policy "authenticated delete modelo_anexo_secoes"
on public.modelo_anexo_secoes
for delete
to authenticated
using (true);
